### ISSUE TITLE
this algorithm is itemCF ?

### ISSUE THREAD

**Issue by YunzeGao** [Giyn/DoubanMovieRecommendationSystem#1]

**Comment by Giyn** [comment]
I will reply to you after I finish my final exam.


giyn.jy@gmail.com
 
From: YunzeGao
Date: 2021-01-05 16:19
To: Giyn/DoubanMovieRecommendationSystem
CC: Subscribed
Subject: [Giyn/DoubanMovieRecommendationSystem] this algorithm is itemCF ? (#1)

**Comment by Giyn** [comment]
Can I ask where is the problem? I haven't made a recommendation system for a long time.
